### ISSUE TITLE
Update Az Functions runtime to 2.0

### ISSUE THREAD

**Issue by kevbite** [dotnetsheff/dotnetsheff-api#4]
Let's update the project to the latest version of azure functions so we don't need to run everything on windows 🎉

**Comment by sakisk** [comment]
There are some [guidelines ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#migrating-from-1x-to-2x) to do this migration. [Suggests ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#migrating-a-locally-developed-application)to create a new azfunc2 project and migrate the old functions to new project. @kevbite

**Comment by kevbite** [comment]
Sounds good to me 👍

**Comment by sakisk** [comment]
I'm tempted to get rid off Refit from the new project.
